### ISSUE TITLE
Issues with timechecker.py execution on non atmos datasets

### ISSUE THREAD

**Issue by TonyB9000** [E3SM-Project/esgfpub#12]
Similar to "time_name in ['time','Time']", I think we need "unit_name" in ['units','Units']"

Traceback (most recent call last):
  File "/p/user_pub/e3sm/bartoletti1/Pub_Work/1_Refactor/Validation/timechecker.py", line 148, in <module>
    sys.exit(main())
  File "/p/user_pub/e3sm/bartoletti1/Pub_Work/1_Refactor/Validation/timechecker.py", line 88, in main
    time_units, time_name = get_time_units(files[0])
  File "/p/user_pub/e3sm/bartoletti1/Pub_Work/1_Refactor/Validation/timechecker.py", line 27, in get_time_units
    return ds[time_name].attrs['units'], time_name
KeyError: 'units'

**Comment by TonyB9000** [comment]
I forgot which file got most of the editing there.  Dataset.py?

**Comment by sterlingbaldwin** [comment]
Fixed
